### ISSUE TITLE
[Question]: Agent workflow question

### ISSUE THREAD

**Issue by nickpending** [evilsocket/nerve#55]
### What is your question?

After reading the examples and documentation I'm a little confused how to chain agents together when the first agent gets data from a tool use. Can you help me understand? Right now I'm just trying to wire it into a workflow where a second dumb agent will echo back the output..

```yaml
name: get-fqdns
description: Fetch today’s new FQDNs for a domain
generator: "anthropic/claude-3-5-sonnet-20240620"

agent: |
  You are a domain-enumeration specialist.
  1. Run `get_fqdns` once to fetch `{{output}}.json`.  
  2. Run `check_json` once to inspect its structure.  
  3. **AI-task**: Analyze the JSON and invoke:
     ```
     run_jq(filter='<your jq expression>')
     ```
  4. **Then stop**—output only the raw FQDNs from `run_jq`, one per line, no extra text.

task: Fetch all FQDNs for domain {{domain}}

using:
  - filesystem

tools:
  - name: get_fqdns
    description: Fetch today’s new FQDNs via censyspy into JSON
    tool: >
      censyspy \
        --data-type both \
        --max-pages -1 \
        --page-size 100 \
        --domain {{domain}} \
        --output {{output}}.json \
        --days 1

  - name: check_json
    description: Peek at the JSON structure
    tool: |
      cat {{output}}.json | head -n30
      echo '───'
      cat {{output}}.json | tail -n30

  - name: run_jq
    description: Run a jq filter to extract FQDNs
    arguments:
      - name: filter
        description: The jq expression to pull out FQDNs (e.g. `.[] | .fqdn`)
    tool: jq -r {{ filter }} {{ output }}.json  
    complete_task: true 
    print: true         

```
